import type { VirtualFile } from "../storage";

export interface UnifiedFileDiff { path: string; status: "added" | "modified" | "deleted" | "unchanged"; patch: string; additions: number; deletions: number; }

export function diffText(path: string, before: string | null, after: string | null): UnifiedFileDiff { if (before === after) return { path, status: "unchanged", patch: "", additions: 0, deletions: 0 }; const beforeLines = before === null ? [] : splitLines(before); const afterLines = after === null ? [] : splitLines(after); const operations = lineOperations(beforeLines, afterLines); let additions = 0; let deletions = 0; const lines = [`--- ${before === null ? "/dev/null" : `a/${path}`}`, `+++ ${after === null ? "/dev/null" : `b/${path}`}`, `@@ -1,${beforeLines.length} +1,${afterLines.length} @@`]; for (const operation of operations) { if (operation.kind === "add") { additions += 1; lines.push(`+${operation.value}`); } else if (operation.kind === "delete") { deletions += 1; lines.push(`-${operation.value}`); } else lines.push(` ${operation.value}`); } return { path, status: before === null ? "added" : after === null ? "deleted" : "modified", patch: lines.join("\n"), additions, deletions }; }

export function diffFiles(before: VirtualFile[], after: VirtualFile[]): UnifiedFileDiff[] { const paths = [...new Set([...before.map((file) => file.path), ...after.map((file) => file.path)])].sort(); const beforeMap = new Map(before.map((file) => [file.path, file.content])); const afterMap = new Map(after.map((file) => [file.path, file.content])); return paths.map((path) => diffText(path, beforeMap.get(path) ?? null, afterMap.get(path) ?? null)).filter((diff) => diff.status !== "unchanged"); }

function splitLines(value: string): string[] { return value.replace(/\r\n/g, "\n").split("\n"); }
type Operation = { kind: "same" | "add" | "delete"; value: string };
function lineOperations(before: string[], after: string[]): Operation[] { const rows = before.length + 1; const cols = after.length + 1; const table: number[][] = Array.from({ length: rows }, () => Array<number>(cols).fill(0)); for (let row = before.length - 1; row >= 0; row -= 1) for (let col = after.length - 1; col >= 0; col -= 1) table[row][col] = before[row] === after[col] ? table[row + 1][col + 1] + 1 : Math.max(table[row + 1][col], table[row][col + 1]); const operations: Operation[] = []; let row = 0; let col = 0; while (row < before.length && col < after.length) { if (before[row] === after[col]) { operations.push({ kind: "same", value: before[row] }); row += 1; col += 1; } else if (table[row + 1][col] >= table[row][col + 1]) { operations.push({ kind: "delete", value: before[row++] }); } else operations.push({ kind: "add", value: after[col++] }); } while (row < before.length) operations.push({ kind: "delete", value: before[row++] }); while (col < after.length) operations.push({ kind: "add", value: after[col++] }); return operations; }
