export type VfsBranchName = "main" | "experimental";
export interface VfsBranch { name: VfsBranchName; headSnapshotId: string | null; updatedAt: number; }

const DATABASE = "mobile-agentic-ide-vfs-history";
const VERSION = 1;
const STORE = "branches";

export async function listBranches(): Promise<VfsBranch[]> { await ensureBranches(); return request<VfsBranch[]>("readonly", (store) => store.getAll()); }
export async function getCurrentBranch(): Promise<VfsBranchName> { if (typeof localStorage !== "undefined") { const value = localStorage.getItem("mobile-agentic-ide:vfs-branch"); if (value === "main" || value === "experimental") return value; } return "main"; }
export async function getBranch(name: VfsBranchName): Promise<VfsBranch | null> { await ensureBranches(); return (await request<VfsBranch | undefined>("readonly", (store) => store.get(name))) ?? null; }
export async function switchBranch(name: VfsBranchName): Promise<VfsBranch> { await ensureBranches(); const existing = await getBranch(name); const branch = existing ?? { name, headSnapshotId: null, updatedAt: Date.now() }; await request("readwrite", (store) => store.put(branch)); if (typeof localStorage !== "undefined") localStorage.setItem("mobile-agentic-ide:vfs-branch", name); return branch; }
export async function updateBranchHead(name: VfsBranchName, headSnapshotId: string | null): Promise<VfsBranch> { const branch = (await getBranch(name)) ?? { name, headSnapshotId: null, updatedAt: Date.now() }; const updated = { ...branch, headSnapshotId, updatedAt: Date.now() }; await request("readwrite", (store) => store.put(updated)); return updated; }

async function ensureBranches(): Promise<void> { const database = await openDatabase(); const existing = await new Promise<VfsBranch[]>((resolve, reject) => { const transaction = database.transaction(STORE, "readonly"); const get = transaction.objectStore(STORE).getAll(); get.onsuccess = () => resolve(get.result as VfsBranch[]); get.onerror = () => reject(get.error); }); database.close(); if (existing.length >= 2) return; const transactionDb = await openDatabase(); await new Promise<void>((resolve, reject) => { const transaction = transactionDb.transaction(STORE, "readwrite"); const store = transaction.objectStore(STORE); for (const name of ["main", "experimental"] as VfsBranchName[]) if (!existing.some((branch) => branch.name === name)) store.put({ name, headSnapshotId: null, updatedAt: Date.now() } satisfies VfsBranch); transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error); }); transactionDb.close(); }
function openDatabase(): Promise<IDBDatabase> { if (typeof indexedDB === "undefined") return Promise.reject(new Error("IndexedDB is not available in this browser.")); return new Promise((resolve, reject) => { const request = indexedDB.open(DATABASE, VERSION); request.onupgradeneeded = () => { if (!request.result.objectStoreNames.contains("snapshots")) request.result.createObjectStore("snapshots", { keyPath: "id" }); if (!request.result.objectStoreNames.contains(STORE)) request.result.createObjectStore(STORE, { keyPath: "name" }); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
function request<T = IDBValidKey>(mode: IDBTransactionMode, operation: (store: IDBObjectStore) => IDBRequest<T>): Promise<T> { return openDatabase().then((database) => new Promise((resolve, reject) => { const transaction = database.transaction(STORE, mode); const result = operation(transaction.objectStore(STORE)); result.onsuccess = () => resolve(result.result); result.onerror = () => reject(result.error); transaction.oncomplete = () => database.close(); transaction.onerror = () => reject(transaction.error); })); }
