import { createFile, listDirectories, listFiles, readFile, updateFile } from "../storage";
import { polyglotEngine, wasmContainer } from "../wasm";
import { githubAdapter, googleAdapter, invokeIntegration, listIntegrations, tokenVault } from "../integrations";
import { runVirtualTests } from "../testing";
import { vfsHistory, switchBranch, workspaceTransaction, type VfsBranchName } from "../vfs";
import { processScheduler } from "./processScheduler";
import { collectSystemHealth } from "../system";
import type { ToolCall, ToolDefinition } from "./types";

const confirmation = { type: "boolean", description: "Must be true to authorize an external mutation." };
export const workspaceTools: ToolDefinition[] = [
  { name: "read_file", description: "Read one device-local workspace file by relative path. A VFS checkpoint is created first.", parameters: { type: "object", properties: { path: { type: "string" } }, required: ["path"] } },
  { name: "write_file", description: "Create or replace one device-local workspace file. A VFS checkpoint is created first.", parameters: { type: "object", properties: { path: { type: "string" }, content: { type: "string" } }, required: ["path", "content"] } },
  { name: "list_files", description: "List device-local files and directories.", parameters: { type: "object", properties: {} } },
  { name: "execute_command", description: "Run one supported command inside the Wasm POSIX sandbox. A VFS checkpoint is created first.", parameters: { type: "object", properties: { command: { type: "string" }, env: { type: "object", additionalProperties: { type: "string" } } }, required: ["command"] } },
  { name: "execute_code", description: "Execute JavaScript with node or the supported Python3 bridge inside the Wasm sandbox.", parameters: { type: "object", properties: { language: { type: "string", enum: ["node", "python3"] }, code: { type: "string" }, filename: { type: "string" } }, required: ["language", "code"] } },
  { name: "run_tests", description: "Run the in-browser Test Matrix against the current IndexedDB workspace.", parameters: { type: "object", properties: {} } },
  { name: "vfs_checkpoint", description: "Create a named point-in-time snapshot of all IndexedDB files and directories.", parameters: { type: "object", properties: { label: { type: "string" } } } },
  { name: "vfs_rollback", description: "Restore the workspace to a checkpoint snapshot, or the latest checkpoint on the active branch.", parameters: { type: "object", properties: { snapshotId: { type: "string" } } } },
  { name: "vfs_diff", description: "Calculate unified line-by-line diffs between a checkpoint and the current workspace.", parameters: { type: "object", properties: { snapshotId: { type: "string" } } } },
  { name: "vfs_switch_branch", description: "Switch the active lightweight virtual branch between main and experimental.", parameters: { type: "object", properties: { branch: { type: "string", enum: ["main", "experimental"] } }, required: ["branch"] } },
  { name: "vfs_list_branches", description: "List virtual branches, their checkpoint heads, and the active branch.", parameters: { type: "object", properties: {} } },
  { name: "process_schedule", description: "Queue a non-blocking command in the persistent local process scheduler.", parameters: { type: "object", properties: { command: { type: "string" }, env: { type: "object", additionalProperties: { type: "string" } } }, required: ["command"] } },
  { name: "process_status", description: "Read one scheduled process or the recent process queue, including queued, running, completed, failed, and cancelled states.", parameters: { type: "object", properties: { processId: { type: "string" } } } },
  { name: "process_logs", description: "Read persisted stdout, stderr, status, error, and tool execution logs for a scheduled process.", parameters: { type: "object", properties: { processId: { type: "string" } } } },
  { name: "process_kill", description: "Cancel a queued or running scheduled process using its process ID.", parameters: { type: "object", properties: { processId: { type: "string" } }, required: ["processId"] } },
  { name: "spawn_sub_agent", description: "Queue a bounded child-agent task asynchronously with its own prompt, system instructions, and allowed tool names. Returns a process ID for status and logs.", parameters: { type: "object", properties: { prompt: { type: "string" }, systemInstructions: { type: "string" }, allowedTools: { type: "array", items: { type: "string" }, maxItems: 24 } }, required: ["prompt"] } },
  { name: "system_health", description: "Collect storage quota, Wasm memory, process, provider vault, and MCP relay/server health diagnostics without exposing secrets.", parameters: { type: "object", properties: {} } },
  { name: "project_manifest", description: "Read or create the local project.manifest.json runtime capability and dependency declaration.", parameters: { type: "object", properties: {} } },
  { name: "project_import_zip", description: "Import a ZIP archive supplied as base64 into the device-local VFS with size and secret checks.", parameters: { type: "object", properties: { base64: { type: "string" } }, required: ["base64"] } },
  { name: "workspace_transaction", description: "Apply bounded multi-file changes atomically, run the Test Matrix, and roll back on failure.", parameters: { type: "object", properties: { changes: { type: "array", maxItems: 50, items: { type: "object", properties: { path: { type: "string" }, content: { type: "string" } }, required: ["path", "content"] } } }, required: ["changes"] } },
  { name: "integration_status", description: "Check whether GitHub or Google OAuth tokens are configured locally without exposing token values.", parameters: { type: "object", properties: {} } },
  { name: "github_clone", description: "Read a GitHub repository tree into a structured result for the local workspace.", parameters: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, branch: { type: "string" } }, required: ["owner", "repo"] } },
  { name: "github_create_branch", description: "Create a GitHub branch. Requires explicit confirmation.", parameters: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, branch: { type: "string" }, fromBranch: { type: "string" }, confirm: confirmation }, required: ["owner", "repo", "branch", "confirm"] } },
  { name: "github_commit_vfs", description: "Commit all IndexedDB VFS files to a GitHub branch. Requires explicit confirmation.", parameters: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, branch: { type: "string" }, message: { type: "string" }, confirm: confirmation }, required: ["owner", "repo", "branch", "message", "confirm"] } },
  { name: "github_open_pr", description: "Open a GitHub pull request. Requires explicit confirmation.", parameters: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, head: { type: "string" }, base: { type: "string" }, title: { type: "string" }, body: { type: "string" }, confirm: confirmation }, required: ["owner", "repo", "head", "base", "title", "confirm"] } },
  { name: "google_read_doc", description: "Read text context from a Google Doc using the local Google OAuth token.", parameters: { type: "object", properties: { documentId: { type: "string" } }, required: ["documentId"] } },
  { name: "google_write_doc", description: "Replace the text of a Google Doc. Requires explicit confirmation.", parameters: { type: "object", properties: { documentId: { type: "string" }, text: { type: "string" }, confirm: confirmation }, required: ["documentId", "text", "confirm"] } },
  { name: "google_export_vfs", description: "Export the current IndexedDB VFS manifest to Google Drive. Requires explicit confirmation.", parameters: { type: "object", properties: { name: { type: "string" }, confirm: confirmation }, required: ["name", "confirm"] } },
  { name: "github_list_issues", description: "List GitHub issues through the registered GitHub provider.", parameters: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, state: { type: "string" } }, required: ["owner", "repo"] } },
  { name: "github_create_issue", description: "Create a GitHub issue. Requires explicit confirmation.", parameters: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, title: { type: "string" }, body: { type: "string" }, confirm: confirmation }, required: ["owner", "repo", "title", "confirm"] } },
  { name: "integration_request", description: "Call any registered provider operation, including future MCP-backed providers. Requires explicit confirmation.", parameters: { type: "object", properties: { providerId: { type: "string" }, operation: { type: "string" }, input: { type: "object" }, confirm: confirmation }, required: ["providerId", "operation", "input", "confirm"] } },
];

export async function executeWorkspaceTool(call: ToolCall): Promise<string> {
  if (call.name === "read_file" || call.name === "write_file" || call.name === "execute_command") await vfsHistory.checkpoint(`before ${call.name}`);
  const path = typeof call.arguments.path === "string" ? call.arguments.path : "";
  if (call.name === "read_file") { const file = await readFile(path); if (!file) throw new Error(`File not found: ${path}`); return file.content; }
  if (call.name === "write_file") { const content = typeof call.arguments.content === "string" ? call.arguments.content : ""; const result = await workspaceTransaction.apply([{ path, content }]); if (!result.committed) throw new Error(`Write rolled back because verification failed: ${result.testResult.logs.at(-1) ?? "tests failed"}`); return `wrote ${path}`; }
  if (call.name === "list_files") { const [files, directories] = await Promise.all([listFiles(), listDirectories()]); return JSON.stringify({ files: files.map((file) => file.path), directories }); }
  if (call.name === "execute_command") { if (typeof call.arguments.command !== "string") throw new Error("execute_command requires a command string"); const result = await wasmContainer.execute(call.arguments.command, { env: readEnvironment(call.arguments.env) }); if (result.exitCode !== 0) throw new Error(result.stderr || `Command exited with code ${result.exitCode}`); return result.stdout; }
  if (call.name === "execute_code") { const language = call.arguments.language === "python3" ? "python3" : call.arguments.language === "node" ? "node" : null; if (!language || typeof call.arguments.code !== "string") throw new Error("execute_code requires language=node|python3 and code"); const result = await polyglotEngine.run(language, call.arguments.code, { filename: typeof call.arguments.filename === "string" ? call.arguments.filename : language === "node" ? "index.js" : "main.py" }); if (result.exitCode !== 0) throw new Error(result.stderr || `Code exited with code ${result.exitCode}`); return result.stdout; }
  if (call.name === "run_tests") return JSON.stringify(await runVirtualTests(await listFiles()));
  if (call.name === "vfs_checkpoint") return JSON.stringify(await vfsHistory.checkpoint(optionalString(call, "label") ?? "manual checkpoint"));
  if (call.name === "vfs_rollback") return JSON.stringify(await vfsHistory.rollback(optionalString(call, "snapshotId")));
  if (call.name === "vfs_diff") return JSON.stringify(await vfsHistory.diffAgainst(optionalString(call, "snapshotId")));
  if (call.name === "vfs_switch_branch") { const branch = call.arguments.branch === "experimental" ? "experimental" : call.arguments.branch === "main" ? "main" : null; if (!branch) throw new Error("vfs_switch_branch requires branch=main|experimental"); return JSON.stringify(await switchBranch(branch)); }
  if (call.name === "vfs_list_branches") return JSON.stringify(await vfsHistory.branches());
  if (call.name === "process_schedule") { const command = stringArg(call, "command"); return JSON.stringify(await processScheduler.schedule(command, readEnvironment(call.arguments.env))); }
  if (call.name === "process_status") return JSON.stringify(await processScheduler.status(optionalString(call, "processId")));
  if (call.name === "process_logs") return JSON.stringify(await processScheduler.logs(optionalString(call, "processId")));
  if (call.name === "process_kill") return JSON.stringify(await processScheduler.kill(stringArg(call, "processId")));
  if (call.name === "spawn_sub_agent") { const allowedTools = Array.isArray(call.arguments.allowedTools) ? call.arguments.allowedTools.filter((tool): tool is string => typeof tool === "string") : undefined; return JSON.stringify(await processScheduler.scheduleSubAgent({ prompt: stringArg(call, "prompt"), systemInstructions: optionalString(call, "systemInstructions"), allowedTools })); }
  if (call.name === "system_health") return JSON.stringify(await collectSystemHealth());
  if (call.name === "project_manifest") { const { readProjectManifest } = await import("../vfs/projectManager"); return JSON.stringify(await readProjectManifest()); }
  if (call.name === "project_import_zip") { const { importProjectZip } = await import("../vfs/projectManager"); const encoded = stringArg(call, "base64"); const binary = Uint8Array.from(atob(encoded), (char) => char.charCodeAt(0)); return JSON.stringify(await importProjectZip(binary)); }
  if (call.name === "workspace_transaction") { const changes = Array.isArray(call.arguments.changes) ? call.arguments.changes : []; if (changes.length > 50 || changes.some((change) => !change || typeof change.path !== "string" || typeof change.content !== "string")) throw new Error("workspace_transaction requires up to 50 {path, content} changes."); const result = await workspaceTransaction.apply(changes as Array<{ path: string; content: string }>); if (!result.committed) throw new Error(`Transaction rolled back: ${result.testResult.logs.at(-1) ?? "tests failed"}`); return JSON.stringify({ committed: true, changedPaths: result.changedPaths, tests: result.testResult }); }
  if (call.name === "integration_status") return JSON.stringify({ providers: listIntegrations(), configured: { github: await tokenVault.has("github"), google: await tokenVault.has("google") } });
  if (call.name === "github_clone") return JSON.stringify(await githubAdapter.cloneRepository(stringArg(call, "owner"), stringArg(call, "repo"), optionalString(call, "branch") ?? "main"));
  if (call.name === "github_create_branch") { requireConfirmation(call); await githubAdapter.createBranch(stringArg(call, "owner"), stringArg(call, "repo"), stringArg(call, "branch"), optionalString(call, "fromBranch") ?? "main"); return `created GitHub branch ${call.arguments.branch}`; }
  if (call.name === "github_commit_vfs") { requireConfirmation(call); return JSON.stringify(await githubAdapter.commitVfs(stringArg(call, "owner"), stringArg(call, "repo"), stringArg(call, "branch"), stringArg(call, "message"))); }
  if (call.name === "github_open_pr") { requireConfirmation(call); return JSON.stringify(await githubAdapter.openPullRequest(stringArg(call, "owner"), stringArg(call, "repo"), stringArg(call, "head"), stringArg(call, "base"), stringArg(call, "title"), optionalString(call, "body") ?? "")); }
  if (call.name === "google_read_doc") return JSON.stringify(await googleAdapter.readDocument(stringArg(call, "documentId")));
  if (call.name === "google_write_doc") { requireConfirmation(call); return JSON.stringify(await googleAdapter.writeDocument(stringArg(call, "documentId"), stringArg(call, "text"))); }
  if (call.name === "google_export_vfs") { requireConfirmation(call); return JSON.stringify(await googleAdapter.exportVfsToDrive(stringArg(call, "name"))); }
  if (call.name === "github_list_issues") return JSON.stringify(await invokeIntegration("github", "listIssues", { owner: stringArg(call, "owner"), repo: stringArg(call, "repo"), state: optionalString(call, "state") ?? "open" }));
  if (call.name === "github_create_issue") { requireConfirmation(call); return JSON.stringify(await invokeIntegration("github", "createIssue", { owner: stringArg(call, "owner"), repo: stringArg(call, "repo"), title: stringArg(call, "title"), body: optionalString(call, "body") ?? "" })); }
  if (call.name === "integration_request") { if (call.arguments.confirm === true) return JSON.stringify(await invokeIntegration(stringArg(call, "providerId"), stringArg(call, "operation"), (call.arguments.input ?? {}) as Record<string, unknown>)); throw new Error("integration_request requires confirm: true because provider operations may be external."); }
  throw new Error(`Unsupported workspace tool: ${call.name}`);
}

function stringArg(call: ToolCall, key: string): string { const value = call.arguments[key]; if (typeof value !== "string" || !value.trim()) throw new Error(`${call.name} requires ${key}`); return value.trim(); }
function optionalString(call: ToolCall, key: string): string | undefined { return typeof call.arguments[key] === "string" ? call.arguments[key] as string : undefined; }
function requireConfirmation(call: ToolCall): void { if (call.arguments.confirm !== true) throw new Error(`${call.name} is an external mutation and requires confirm: true.`); }
function readEnvironment(value: unknown): Record<string, string> | undefined { if (!value || typeof value !== "object") return undefined; return Object.fromEntries(Object.entries(value).filter((entry): entry is [string, string] => typeof entry[0] === "string" && typeof entry[1] === "string")); }
