import { logStorage } from "../agent/logStorage";
import { processScheduler } from "../agent/processScheduler";
import { tokenVault } from "../integrations";
import { storageManager } from "../vfs";
import { wasmContainer } from "../wasm";

export interface SystemHealth { checkedAt: string; storage: Awaited<ReturnType<typeof storageManager.estimate>>; wasm: { memoryBytes: number; memoryPages: number; activeProcesses: number; executionCount: number; lastExecutionMs: number }; processes: { active: number; queued: number; running: number; completed: number; failed: number; cancelled: number; logs: number }; vault: { githubConfigured: boolean; googleConfigured: boolean }; mcp: { server: { status: string; connectedClients: number; handledRequests: number; endpoint: string }; relay: { status: string; sessionId: string | null; publicUrl: string | null; reconnectAttempt: number; nextRetryMs: number | null; lastHeartbeatAt: number | null } }; }

export async function collectSystemHealth(): Promise<SystemHealth> { const [{ mcpRelay, mcpServer }, storage, processes, logs, githubConfigured, googleConfigured] = await Promise.all([import("../mcp"), storageManager.estimate(), processScheduler.status(), logStorage.listLogs(), tokenVault.has("github"), tokenVault.has("google")]); const records = Array.isArray(processes) ? processes : [processes]; const metrics = wasmContainer.getMetrics(); return { checkedAt: new Date().toISOString(), storage, wasm: { memoryBytes: metrics.memoryBytes, memoryPages: metrics.memoryPages, activeProcesses: metrics.process.activeProcesses, executionCount: metrics.executionCount, lastExecutionMs: metrics.lastExecutionMs }, processes: { active: records.filter((process) => process.status === "running").length, queued: records.filter((process) => process.status === "queued").length, running: records.filter((process) => process.status === "running").length, completed: records.filter((process) => process.status === "completed").length, failed: records.filter((process) => process.status === "failed").length, cancelled: records.filter((process) => process.status === "cancelled").length, logs: logs.length }, vault: { githubConfigured, googleConfigured }, mcp: { server: mcpServer.getStatus(), relay: mcpRelay.getSnapshot() } }; }
