import { useEffect, useMemo, useState } from "react";
import { mcpServer } from "../../lib/mcp";

export function McpControlPanel() {
  const [status, setStatus] = useState(() => mcpServer.getStatus());
  const [message, setMessage] = useState("");
  const endpoint = useMemo(() => `${window.location.origin}/mcp`, []);
  const configuration = useMemo(() => JSON.stringify({ mcpServers: { "mobile-agentic-ide": { url: endpoint, transport: "sse" } }, chatgptCustomAction: { openapi: "3.1.0", info: { title: "Mobile Agentic IDE MCP", version: "1.0.0" }, servers: [{ url: endpoint }], paths: { "/": { post: { operationId: "mcpJsonRpc", summary: "Send an MCP JSON-RPC request", requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: true } } } }, responses: { "200": { description: "MCP JSON-RPC response" } } } } } }, note: "Browser bridge endpoint; external reachability requires an HTTPS-capable host or reverse proxy." }, null, 2), [endpoint]);

  useEffect(() => { const timer = window.setInterval(() => setStatus(mcpServer.getStatus("/mcp")), 1000); return () => window.clearInterval(timer); }, []);
  async function copyConfiguration(): Promise<void> { try { await navigator.clipboard.writeText(configuration); setMessage("MCP configuration copied."); } catch { setMessage("Clipboard access unavailable; select and copy the configuration manually."); } }

  return <section id="mcp" className="workspace-card mcp-card" aria-labelledby="mcp-title"><div className="status-row"><span className="status-dot" aria-hidden="true" /><span>MCP browser bridge · {status.status === "initialized" ? "Connected" : "Listening"}</span></div><h2 id="mcp-title">Connect external agents.</h2><p className="workspace-intro">Expose the local VFS, Wasm execution, test, and registered ecosystem tools through JSON-RPC 2.0 MCP methods.</p><div className="ledger-state mcp-stats"><div><span className="ledger-label">Server</span><strong>{status.status === "initialized" ? "Initialized" : "Ready"}</strong></div><div><span className="ledger-label">Connected clients</span><strong>{status.connectedClients}</strong></div><div><span className="ledger-label">Handled requests</span><strong>{status.handledRequests}</strong></div></div><label className="ledger-label" htmlFor="mcp-endpoint">MCP Connection Endpoint URL</label><div className="input-row"><input id="mcp-endpoint" value={endpoint} readOnly /><button className="primary-button" type="button" onClick={() => { void navigator.clipboard.writeText(endpoint).then(() => setMessage("Endpoint copied."), () => setMessage("Clipboard access unavailable.")); }}>Copy</button></div><div className="mcp-notice"><strong>Browser bridge limitation</strong><span>The PWA can handle MCP requests through its HTTP/SSE adapter when hosted behind a reachable HTTPS route. A standalone browser tab cannot open an inbound public TCP listener.</span></div><label className="ledger-label" htmlFor="mcp-config">MCP Configuration JSON</label><textarea id="mcp-config" value={configuration} readOnly spellCheck={false} /><button className="handover-button" type="button" onClick={() => { void copyConfiguration(); }}>Copy MCP Configuration JSON <span aria-hidden="true">↗</span></button>{message && <p className="agent-output" aria-live="polite">{message}</p>}<p className="scope-note">Methods: initialize · ping · tools/list · tools/call · SSE + HTTP POST.</p></section>;
}
